name: "Check PR"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-main
  cancel-in-progress: true

env:
  REPOSITORY_TYPE: public
  MODEL_URL: "https://github.com/fipl-hse/2025-2-level-ctlr/releases/download/v1.0.0/russian-syntagrus-ud-2.0-170801.udpipe"
  MODEL_PATH: "lab_6_pipeline/assets/model"

jobs:
  install-dependencies:
    name: Installing dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Confirming everything is OK
        run: |
          ls -la venv

  pr-name-check:
    name: PR name check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    timeout-minutes: 5
    needs: [install-dependencies]
    env:
      PR_NAME: ${{ github.event.pull_request.title }}
      PR_AUTHOR: ${{ github.actor }}

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: PR name check
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          fiplconfig.check_pr_name --pr_name "$PR_NAME" --pr_author "$PR_AUTHOR"

  code-style:
    name: Code Style
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [install-dependencies]

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Code Style
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          fiplconfig.check_lint --repository-type "$REPOSITORY_TYPE"

  mypy-checks:
    name: Mypy checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [install-dependencies]

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: MyPy check
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          fiplconfig.check_mypy

  flake8-checks:
    name: Import style checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [install-dependencies]

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Flake8 check
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          fiplconfig.check_flake8

  requirements-check:
    name: Requirements check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [install-dependencies]

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Dependencies check
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          fiplconfig.check_requirements

  newline-check:
    name: Newline check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [install-dependencies]

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Newline check
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          fiplconfig.check_newline

  checking-module-usage:
    name: Prohibited module usage check
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Run module_usage_check
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          fiplconfig.check_module_usage

  # Stage 2. Crawler tests
  checking-crawler-config:
    name: Crawler checks config
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Run crawler config checks
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          fiplconfig.run_tests --lab-path lab_5_scraper --pytest-label stage_2_1_crawler_config_check

  checking-crawler:
    name: Crawler checks
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Run crawler checks
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          fiplconfig.run_tests --lab-path lab_5_scraper --pytest-label stage_2_2_crawler_check

  checking-parser:
    name: Parser checks
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Run HTML parser checks
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          fiplconfig.run_tests --lab-path lab_5_scraper --pytest-label stage_2_3_HTML_parser_check

  collecting-articles-from-internet:
    name: Download articles
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Crawl a raw dataset from web
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)

          if [[ $(python admin_utils/skip_stage.py --lab-path lab_5_scraper) ]]; then
            exit 0
          fi

          python admin_utils/config_param_changer.py --config_path="lab_5_scraper/scraper_config.json"
          echo "Changed config params"
          python lab_5_scraper/scraper.py
          ls -la tmp/articles

          fiplconfig.run_tests --lab-path lab_5_scraper --pytest-label stage_2_4_dataset_volume_check
      - name: Archive raw dataset
        uses: actions/upload-artifact@v6
        with:
          name: raw-dataset
          path: |
            tmp/articles
          retention-days: 5

  checking-articles-dataset:
    name: Validate dataset
    needs: [collecting-articles-from-internet]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Download previously collected dataset
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: raw-dataset
      - name: Run metadata validation
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd):$PYTHONPATH
          python admin_utils/unpack_archived_dataset.py lab_5_scraper
          fiplconfig.run_tests --lab-path lab_5_scraper --pytest-label stage_2_5_dataset_validation

  milestone-1-crawler-is-working:
    name: Crawler is accepted!
    needs: [checking-articles-dataset]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    outputs:
      should_run: ${{ steps.pipeline-check.outputs.should_run }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Congratulations
        run: |
          echo "You have completed the crawler!"
      - name: Check for pipeline
        id: pipeline-check
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd):$PYTHONPATH
          
          if [[ $(python admin_utils/skip_stage.py --lab-path lab_6_pipeline) ]]; then
            echo "No pipeline to run."
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "No reason to skip pipeline."
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi

  # Stage 3. Pipeline tests
  milestone-2-pipeline:
    name: Starting pipeline checks!
    needs: [milestone-1-crawler-is-working]
    if: needs.milestone-1-crawler-is-working.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Allowed to run pipeline
        run: |
          echo "Preparing pipeline checks"

  checking-raw-dataset-before-running-pipeline:
    name: Pipe verifies dataset
    needs: [milestone-2-pipeline]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Download previously collected dataset
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: raw-dataset
      - name: Run dataset sanity checks
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          fiplconfig.run_tests --lab-path lab_6_pipeline --pytest-label stage_3_1_dataset_sanity_checks

  checking-corpus-manager-creates-instances-correctly:
    name: CorpusManager detects articles
    needs: [milestone-2-pipeline]
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Download previously collected dataset
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: raw-dataset
      - name: Run CorpusManager tests
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd):$PYTHONPATH
          python admin_utils/unpack_archived_dataset.py lab_6_pipeline
          fiplconfig.run_tests --lab-path lab_6_pipeline --pytest-label stage_3_2_corpus_manager_checks

  checking-student-processing-works-for-admin-dataset:
    name: Pipe processed admin data
    needs: [milestone-2-pipeline]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Download previously collected dataset
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: raw-dataset
      - name: Run metadata validation
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd):$PYTHONPATH
          python admin_utils/unpack_archived_dataset.py lab_6_pipeline
          fiplconfig.run_tests --lab-path lab_6_pipeline --pytest-label stage_3_3_admin_data_processing

  run-student-processing:
    name: Pipe processed student data
    needs: [milestone-2-pipeline]
    env:
      PR_AUTHOR: ${{ github.actor }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Download UDPipe model
        run: |
          mkdir -p "$MODEL_PATH"
          wget -O $MODEL_PATH/russian-syntagrus-ud-2.0-170801.udpipe $MODEL_URL
      - name: Download previously collected dataset
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: raw-dataset
      - name: Run validation of `_processed.txt` files
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd):$PYTHONPATH

          python admin_utils/unpack_archived_dataset.py lab_6_pipeline
          python lab_6_pipeline/pipeline.py
          ls -la tmp/articles
      - name: Archive processed dataset
        continue-on-error: true
        uses: actions/upload-artifact@v6
        with:
          name: processed-dataset
          path: |
            tmp/articles
          retention-days: 5

  checking-student-processing-works-for-student-dataset:
    name: Validate final dataset
    needs: [run-student-processing]
    env:
      PR_AUTHOR: ${{ github.actor }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Download UDPipe model
        run: |
          mkdir -p "$MODEL_PATH"
          wget -O $MODEL_PATH/russian-syntagrus-ud-2.0-170801.udpipe $MODEL_URL
      - name: Download previously collected dataset
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: processed-dataset
      - name: Run validation of `_processed.txt` files
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd):$PYTHONPATH
          python admin_utils/unpack_archived_dataset.py lab_6_pipeline
          fiplconfig.run_tests --lab-path lab_6_pipeline --pytest-label stage_3_4_student_dataset_validation

  running-pos-pipeline-tests:
    name: POSFrequencyPipeline tests
    needs:
      [
        checking-raw-dataset-before-running-pipeline,
        checking-student-processing-works-for-admin-dataset,
        checking-student-processing-works-for-student-dataset,
        checking-corpus-manager-creates-instances-correctly,
      ]
    env:
      PR_AUTHOR: ${{ github.actor }}
    runs-on: ubuntu-latest
    timeout-minutes: 7

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Download UDPipe model
        run: |
          mkdir -p "$MODEL_PATH"
          wget -O $MODEL_PATH/russian-syntagrus-ud-2.0-170801.udpipe $MODEL_URL
      - name: Download previously collected dataset
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: processed-dataset
      - name: Run POS frequency pipeline tests
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          fiplconfig.run_tests --lab-path lab_6_pipeline --pytest-label stage_4_pos_frequency_pipeline_checks
      - name: Archive processed dataset
        continue-on-error: true
        uses: actions/upload-artifact@v6
        with:
          name: processed-dataset
          path: |
            tmp/articles
          retention-days: 5

  running-pattern-search-pipeline-tests:
    name: PatternSearchPipeline tests
    needs: [running-pos-pipeline-tests]
    env:
      PR_AUTHOR: ${{ github.actor }}
    runs-on: ubuntu-latest
    timeout-minutes: 7

    steps:
      - uses: actions/checkout@v6
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13.2
      - name: Download UDPipe model
        run: |
          mkdir -p "$MODEL_PATH"
          wget -O $MODEL_PATH/russian-syntagrus-ud-2.0-170801.udpipe $MODEL_URL
      - name: Download previously collected dataset
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: processed-dataset
      - name: Run pattern search pipeline tests
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          fiplconfig.run_tests --lab-path lab_6_pipeline --pytest-label stage_5_pattern_search_pipeline_checks
      - name: Archive processed dataset
        continue-on-error: true
        uses: actions/upload-artifact@v6
        with:
          name: processed-dataset
          path: |
            tmp/articles
          retention-days: 5

  milestone-2-pipeline-is-working:
    name: Pipeline is accepted!
    needs: [running-pattern-search-pipeline-tests]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Congratulations
        run: |
          echo "You have completed the assignment!"
